### PR TITLE
converted time data to local timezone

### PR DESCRIPTION
**Pull request by TheTrio**
Issue: #4 

So unfortunately, I couldn't find a way to seed the database(maybe I missed it in the README) but I tried this with a dummy array and it seems to work.

### CODE REVIEW

**Comment by SysSn13** [comment]
This is not working as intended because you are converting the time on the server side. What we need is to covert the time to the client's time zone. Converting this in ejs template will also not help as templates are also compiled on the server-side.

**Comment by TheTrio** [comment]
How about this? I'm changing the startTime `td` on the client side now.

**Comment by TheTrio** [comment]
Actually, on second thought, `let startTime = new Date(contest.textContent)` ought to be enough since the Date constructor defaults to the local timezone. I haven't been able to confirm this though, given that my local server and my browser are in the same time zone.

**Comment by SysSn13** [comment]
Not working when entries are more than the pagination page size. Also what is the need of using Intl when you can simply use `Date.prototype.toLocaleString()`?

**Comment by SysSn13** [comment]
You can populate the database by running the background service and change [IsLatestContest](https://github.com/SysSn13/leetcode-rating-predictor/blob/main/helpers.js#L22) accordingly.

**Comment by TheTrio** [comment]
So I have fixed the pagination bug by running the code when the page is changed.  As for the timezone, I've removed the redundant parts. Hopefully this suffices. Do let me know if there's anything I can do better.

**Comment by SysSn13** [comment]
Seems good.

**Pull request merged**
